<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction and Dataset Description</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="AdvanceDS_Project1_files/libs/clipboard/clipboard.min.js"></script>
<script src="AdvanceDS_Project1_files/libs/quarto-html/quarto.js"></script>
<script src="AdvanceDS_Project1_files/libs/quarto-html/popper.min.js"></script>
<script src="AdvanceDS_Project1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="AdvanceDS_Project1_files/libs/quarto-html/anchor.min.js"></script>
<link href="AdvanceDS_Project1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="AdvanceDS_Project1_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="AdvanceDS_Project1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="AdvanceDS_Project1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="AdvanceDS_Project1_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><strong>Introduction and Dataset Description</strong></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data-acquisition" class="level1">
<h1><strong>Data Acquisition</strong></h1>
<ul>
<li>In this section, we utilize openFDA’s Food API to explore adverse events related to FDA-regulated foods, dietary supplements, and cosmetics.</li>
<li>Specifically, our focus is on the Soft Drink/Water industry.</li>
<li>Due to API constraints, the maximum value for the limit parameter is currently set at 1000.</li>
</ul>
<div id="cell-5" class="cell" data-outputid="2260aba8-a495-42b2-f02b-34c5b49d568a" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> urllib.request <span class="im">import</span> urlopen</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>data_list <span class="op">=</span> []</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">4000</span>, <span class="dv">1000</span>):</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  url <span class="op">=</span> <span class="ss">f"https://api.fda.gov/food/event.json?search=products.industry_name:%22Soft+Drink/Water%22&amp;skip=</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">&amp;limit=1000"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  response <span class="op">=</span> urlopen(url)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  data_json <span class="op">=</span> json.loads(response.read())</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  data_list.extend(data_json[<span class="st">"results"</span>])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"fda_soft_drink_data.json"</span>, <span class="st">"w"</span>) <span class="im">as</span> <span class="bu">file</span>:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    json.dump(data_list, <span class="bu">file</span>, indent<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Data has been saved to fda_soft_drink_data.json"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data has been saved to fda_soft_drink_data.json</code></pre>
</div>
</div>
<div id="cell-6" class="cell" data-outputid="fbbcb41e-67ca-4ddd-e484-55418014411e">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(data_list)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="72">

  <div id="df-e8e5310b-9c85-4e2d-af6c-4b7a2c13fe2d" class="colab-df-container">
    <div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">report_number</th>
<th data-quarto-table-cell-role="th">outcomes</th>
<th data-quarto-table-cell-role="th">date_created</th>
<th data-quarto-table-cell-role="th">reactions</th>
<th data-quarto-table-cell-role="th">date_started</th>
<th data-quarto-table-cell-role="th">consumer</th>
<th data-quarto-table-cell-role="th">products</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>93655</td>
<td>[Required Intervention, Other Serious or Impor...</td>
<td>20070613</td>
<td>[ANXIETY, ASTHENIA, CONVULSION, DEPRESSION, FA...</td>
<td>20070320</td>
<td>{'age': '17', 'age_unit': 'year(s)', 'gender':...</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'DIET COKE ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>114770</td>
<td>[Other Outcome]</td>
<td>20081021</td>
<td>[VOMITING]</td>
<td>20081020</td>
<td>{'gender': 'Female'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'DASANI PUR...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>153453</td>
<td>[Visited Emergency Room, Visited a Health Care...</td>
<td>20120613</td>
<td>[DYSPHAGIA, FATIGUE, INFECTION, LOCAL SWELLING...</td>
<td>20120422</td>
<td>{'gender': 'Female'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'XXX VITAMI...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>194667</td>
<td>[Visited Emergency Room, Visited a Health Care...</td>
<td>20151007</td>
<td>[ABDOMINAL PAIN, ABDOMINAL PAIN UPPER, APPETIT...</td>
<td>None</td>
<td>{'gender': 'Male'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'FAMILY GOU...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>108237</td>
<td>[Visited Emergency Room]</td>
<td>20081124</td>
<td>[ANAPHYLACTIC SHOCK, DYSPNOEA]</td>
<td>20080703</td>
<td>{'gender': 'Male'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'NIAGRA WAT...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3471</td>
<td>82018</td>
<td>[Other Outcome]</td>
<td>20050114</td>
<td>[PARAESTHESIA]</td>
<td>20050112</td>
<td>{'gender': 'Male'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'KID CONNEC...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3472</td>
<td>94274</td>
<td>[Other Outcome]</td>
<td>20061205</td>
<td>[NECK PAIN, SALIVARY HYPERSECRETION, VISION BL...</td>
<td>20061127</td>
<td>{'gender': 'Male'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'SAM'S CHOI...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3473</td>
<td>188720</td>
<td>[Other Outcome]</td>
<td>20150715</td>
<td>[BURNING SENSATION]</td>
<td>20150715</td>
<td>{'gender': 'Female'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'PUBLIX PUR...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3474</td>
<td>112321</td>
<td>[Visited a Health Care Provider]</td>
<td>20090421</td>
<td>[OESOPHAGEAL ACHALASIA]</td>
<td>20090301</td>
<td>{'age': '14', 'age_unit': 'year(s)', 'gender':...</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'DIET RITE'...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3475</td>
<td>194409</td>
<td>[Visited a Health Care Provider]</td>
<td>20160128</td>
<td>[BLISTER, OEDEMA PERIPHERAL, PRURITUS]</td>
<td>20150120</td>
<td>{'gender': 'Female'}</td>
<td>[{'role': 'SUSPECT', 'name_brand': 'DIET COCA-...</td>
</tr>
</tbody>
</table>

<p>3476 rows × 7 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-e8e5310b-9c85-4e2d-af6c-4b7a2c13fe2d')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-e8e5310b-9c85-4e2d-af6c-4b7a2c13fe2d button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-e8e5310b-9c85-4e2d-af6c-4b7a2c13fe2d');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-aa98ca23-33bc-4380-b363-2e48608376de">
  <button class="colab-df-quickchart" onclick="quickchart('df-aa98ca23-33bc-4380-b363-2e48608376de')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-aa98ca23-33bc-4380-b363-2e48608376de button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>

  <div id="id_b4c198d2-91d9-41f2-9412-8d315ac6de83">
    <style>
      .colab-df-generate {
        background-color: #E8F0FE;
        border: none;
        border-radius: 50%;
        cursor: pointer;
        display: none;
        fill: #1967D2;
        height: 32px;
        padding: 0 0 0 0;
        width: 32px;
      }

      .colab-df-generate:hover {
        background-color: #E2EBFA;
        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
        fill: #174EA6;
      }

      [theme=dark] .colab-df-generate {
        background-color: #3B4455;
        fill: #D2E3FC;
      }

      [theme=dark] .colab-df-generate:hover {
        background-color: #434B5C;
        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
        fill: #FFFFFF;
      }
    </style>
    <button class="colab-df-generate" onclick="generateWithVariable('df')" title="Generate code using this dataframe." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <path d="M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z"></path>
  </svg>
    </button>
    <script>
      (() => {
      const buttonEl =
        document.querySelector('#id_b4c198d2-91d9-41f2-9412-8d315ac6de83 button.colab-df-generate');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      buttonEl.onclick = () => {
        google.colab.notebook.generateWithVariable('df');
      }
      })();
    </script>
  </div>

    </div>
  </div>
</div>
</div>
</section>
<section id="data-cleaning-and-handling-inconsistencies" class="level1">
<h1><strong>Data Cleaning and Handling Inconsistencies</strong></h1>
<p>In this section, we will: - Fix incorrect data formats (e.g., convert date from string to datetime). - Correct the consumer and product columns, which contain data in nested dictionary format, by separating them into individual columns. - Handle lists in the outcomes and reactions columns by creating dummy variables for each item in the list for further analysis. - Remove missing values. - Remove duplicate rows. - Standardize all alphabets to lower case letters.</p>
<p>Lastly, we will show the summary of the unique values for each category.</p>
<div id="cell-9" class="cell" data-outputid="cd29e5a8-8485-43fe-cb73-d09a125388a5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure Proper Datetime Formatting</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'date_created'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'date_created'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y%m</span><span class="sc">%d</span><span class="st">'</span>, errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'date_started'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'date_started'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y%m</span><span class="sc">%d</span><span class="st">'</span>, errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize the 'consumer' column</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>consumer_df <span class="op">=</span> pd.json_normalize(df[<span class="st">'consumer'</span>])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.concat([df.drop(columns<span class="op">=</span>[<span class="st">'consumer'</span>]), consumer_df], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate the 'role' and 'name_brand' from the 'products' column</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'product_role'</span>] <span class="op">=</span> df[<span class="st">'products'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x[<span class="dv">0</span>][<span class="st">'role'</span>] <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>) <span class="kw">and</span> <span class="bu">len</span>(x) <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="va">None</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'product_name_brand'</span>] <span class="op">=</span> df[<span class="st">'products'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x[<span class="dv">0</span>][<span class="st">'name_brand'</span>].lower() <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>) <span class="kw">and</span> <span class="bu">len</span>(x) <span class="op">&gt;</span> <span class="dv">0</span> <span class="kw">and</span> <span class="bu">isinstance</span>(x[<span class="dv">0</span>].get(<span class="st">'name_brand'</span>), <span class="bu">str</span>) <span class="cf">else</span> <span class="va">None</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'products'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop report_number column, product_role and age_unit column since they are not necessary for further analysis</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'report_number'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'age_unit'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>df.drop(columns<span class="op">=</span>[<span class="st">'product_role'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Since data are in list format, flatten the data</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'outcomes'</span>] <span class="op">=</span> df[<span class="st">'outcomes'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>) <span class="cf">else</span> [x]) <span class="op">\</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>                             .explode() <span class="op">\</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>                             .<span class="bu">apply</span>(<span class="kw">lambda</span> x: x.lower() <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">str</span>) <span class="cf">else</span> x) <span class="op">\</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>                             .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'reactions'</span>] <span class="op">=</span> df[<span class="st">'reactions'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: x <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">list</span>) <span class="cf">else</span> [x]) <span class="op">\</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>                                 .explode() <span class="op">\</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>                                 .<span class="bu">apply</span>(<span class="kw">lambda</span> x: x.lower() <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">str</span>) <span class="cf">else</span> x) <span class="op">\</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                                 .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for the 'outcomes' column</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>outcomes_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">'outcomes'</span>], prefix<span class="op">=</span><span class="st">'outcome'</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for the 'reactions' column</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>reactions_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">'reactions'</span>], prefix<span class="op">=</span><span class="st">'reaction'</span>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.concat([df, outcomes_dummies, reactions_dummies], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove missing values</span></span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna()</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the index for dataframe</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="73">

  <div id="df-a5ecbafe-ad03-42a9-a2aa-8426905825dc" class="colab-df-container">
    <div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">outcomes</th>
<th data-quarto-table-cell-role="th">date_created</th>
<th data-quarto-table-cell-role="th">reactions</th>
<th data-quarto-table-cell-role="th">date_started</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">product_name_brand</th>
<th data-quarto-table-cell-role="th">outcome_allergic reaction</th>
<th data-quarto-table-cell-role="th">outcome_congenital anomaly</th>
<th data-quarto-table-cell-role="th">outcome_death</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">reaction_visual acuity reduced</th>
<th data-quarto-table-cell-role="th">reaction_visual disturbance</th>
<th data-quarto-table-cell-role="th">reaction_visual impairment</th>
<th data-quarto-table-cell-role="th">reaction_vitamin b6 increased</th>
<th data-quarto-table-cell-role="th">reaction_vitreous floaters</th>
<th data-quarto-table-cell-role="th">reaction_vomiting</th>
<th data-quarto-table-cell-role="th">reaction_weight decreased</th>
<th data-quarto-table-cell-role="th">reaction_weight increased</th>
<th data-quarto-table-cell-role="th">reaction_wheezing</th>
<th data-quarto-table-cell-role="th">reaction_white blood cell count increased</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>required intervention</td>
<td>2007-06-13</td>
<td>anxiety</td>
<td>2007-03-20</td>
<td>17</td>
<td>Female</td>
<td>diet coke soda</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>visited emergency room</td>
<td>2004-03-26</td>
<td>insomnia</td>
<td>2004-02-18</td>
<td>8</td>
<td>Female</td>
<td>archer farms market xl cooler, orange pineapple</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>other outcome</td>
<td>2007-02-20</td>
<td>obsessive-compulsive disorder</td>
<td>2007-02-16</td>
<td>52</td>
<td>Female</td>
<td>sobe lean diet mango melon beverage</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>other outcome</td>
<td>2015-06-24</td>
<td>restlessness</td>
<td>2015-06-09</td>
<td>4</td>
<td>Male</td>
<td>acadia spring water</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>visited a health care provider</td>
<td>2018-10-13</td>
<td>pain</td>
<td>2018-10-05</td>
<td>44</td>
<td>Male</td>
<td>mt. dew</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1015</td>
<td>death</td>
<td>2023-09-11</td>
<td>vision blurred</td>
<td>2023-09-07</td>
<td>22</td>
<td>Female</td>
<td>ice mountain water</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1016</td>
<td>other serious outcome</td>
<td>2015-08-07</td>
<td>vomiting</td>
<td>2015-07-27</td>
<td>45</td>
<td>Female</td>
<td>gatorade thirst quencher, orange</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1017</td>
<td>visited a health care provider</td>
<td>2017-04-21</td>
<td>diarrhoea</td>
<td>2017-04-01</td>
<td>36.23</td>
<td>Female</td>
<td>michael ochoa cbd water</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1018</td>
<td>other outcome</td>
<td>2007-07-13</td>
<td>malaise</td>
<td>2007-07-12</td>
<td>47.58</td>
<td>Female</td>
<td>sprite fountain drink</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1019</td>
<td>other serious or important medical event</td>
<td>2009-04-21</td>
<td>vomiting</td>
<td>2009-03-01</td>
<td>14</td>
<td>Male</td>
<td>diet rite</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>...</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>1020 rows × 530 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-a5ecbafe-ad03-42a9-a2aa-8426905825dc')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-a5ecbafe-ad03-42a9-a2aa-8426905825dc button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-a5ecbafe-ad03-42a9-a2aa-8426905825dc');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-e4679717-6d19-4b29-8d67-d287dd349638">
  <button class="colab-df-quickchart" onclick="quickchart('df-e4679717-6d19-4b29-8d67-d287dd349638')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-e4679717-6d19-4b29-8d67-d287dd349638 button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>

  <div id="id_66188d3a-9145-4c55-870f-a9c3f312441f">
    <style>
      .colab-df-generate {
        background-color: #E8F0FE;
        border: none;
        border-radius: 50%;
        cursor: pointer;
        display: none;
        fill: #1967D2;
        height: 32px;
        padding: 0 0 0 0;
        width: 32px;
      }

      .colab-df-generate:hover {
        background-color: #E2EBFA;
        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
        fill: #174EA6;
      }

      [theme=dark] .colab-df-generate {
        background-color: #3B4455;
        fill: #D2E3FC;
      }

      [theme=dark] .colab-df-generate:hover {
        background-color: #434B5C;
        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
        fill: #FFFFFF;
      }
    </style>
    <button class="colab-df-generate" onclick="generateWithVariable('df')" title="Generate code using this dataframe." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <path d="M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z"></path>
  </svg>
    </button>
    <script>
      (() => {
      const buttonEl =
        document.querySelector('#id_66188d3a-9145-4c55-870f-a9c3f312441f button.colab-df-generate');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      buttonEl.onclick = () => {
        google.colab.notebook.generateWithVariable('df');
      }
      })();
    </script>
  </div>

    </div>
  </div>
</div>
</div>
<div id="cell-10" class="cell" data-outputid="396ae0a4-c059-4453-df27-51883ea05a82">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>initial_shape <span class="op">=</span> df.shape</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop_duplicates()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Removed </span><span class="sc">{</span>initial_shape[<span class="dv">0</span>] <span class="op">-</span> df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> duplicate rows. New shape: </span><span class="sc">{</span>df<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Unique values after cleaning:"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Outcomes:"</span>, df[<span class="st">'outcomes'</span>].unique())</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Reactions:"</span>, df[<span class="st">'reactions'</span>].unique())</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Age:"</span>, df[<span class="st">'age'</span>].unique())</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Gender:"</span>, df[<span class="st">'gender'</span>].unique())</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Product Name Brand:"</span>, df[<span class="st">'product_name_brand'</span>].unique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Removed 0 duplicate rows. New shape: (1020, 530)
Unique values after cleaning:
Outcomes: ['required intervention' 'visited emergency room' 'other outcome'
 'visited a health care provider' 'hospitalization'
 'other serious or important medical event' 'other serious outcome'
 'life threatening' 'disability' 'allergic reaction' 'congenital anomaly'
 'death']
Reactions: ['anxiety' 'insomnia' 'obsessive-compulsive disorder' 'restlessness'
 'pain' 'abdominal pain upper' 'asthenia' 'dyspnoea' 'abdominal pain'
 'vomiting' 'palpitations' 'feeling abnormal' 'pruritus' 'swelling'
 'diarrhoea' 'food poisoning' 'malaise' 'headache'
 'gastrointestinal disorder' 'bacterial infection' 'nausea' 'colitis'
 'throat irritation' 'dysgeusia' 'hypersensitivity' 'chest discomfort'
 'dry mouth' 'inflammation' 'poisoning' 'psychomotor hyperactivity'
 'tremor' 'vertigo' 'skin irritation' 'fatigue' 'hypoaesthesia'
 'bone pain' 'eye infection' 'adverse reaction'
 'feeling of body temperature change' 'skin burning sensation'
 'gastrointestinal tract irritation' 'convulsion' 'limb discomfort'
 'feeling hot' 'burning sensation' 'heart rate increased' 'eructation'
 'dizziness' 'faecal incontinence' 'paraesthesia' 'blister'
 'hypoventilation' 'adverse event' 'urinary incontinence'
 'gastrooesophageal reflux disease' 'abdominal distension' 'chills'
 'brain injury' 'unresponsive to stimuli' 'blood pressure increased'
 'restless legs syndrome' 'vitamin b6 increased' 'dyspepsia'
 'visual disturbance' 'body temperature increased' 'face oedema'
 'caustic injury' 'hyperhidrosis' 'cough' 'rash papular'
 'urogenital disorder' 'blood glucose increased' 'lung infiltration'
 'oropharyngeal pain' 'pharyngeal erythema' 'salivary hypersecretion'
 'speech disorder' 'tinnitus' 'decreased appetite' 'fall'
 'salivary gland disorder' 'blood pressure fluctuation' 'rash' 'dry skin'
 'erythema' 'viral infection' 'abdominal discomfort' 'anosmia'
 'oropharyngeal blistering' 'pharyngeal oedema' 'dysphagia'
 'oropharyngeal swelling' 'influenza like illness' 'vision blurred'
 'myocardial infarction' 'flushing' 'lip and/or oral cavity cancer'
 'immune system disorder' 'metabolic disorder' 'memory impairment'
 'abnormal behaviour' 'renal failure' 'blood glucose abnormal'
 'polydipsia' 'exophthalmos' 'onychoclasis' 'gastric disorder' 'myalgia'
 'injury' 'discomfort' 'contusion' 'oesophageal pain'
 'product odour abnormal' 'urticaria' 'rhinorrhoea' 'pharyngeal swelling'
 'hypertension' 'liver function test abnormal' 'ageusia' 'depression'
 'visual acuity reduced' 'vaginal haemorrhage' 'death' 'influenza'
 'sleep disorder' 'sepsis' 'dysuria' 'retching' 'chest pain'
 'regurgitation' 'resuscitation' 'feeling jittery' 'multiple sclerosis'
 'optic neuritis' 'flatulence' 'product taste abnormal' 'arthralgia'
 'dysphonia' 'chromaturia' 'hypoaesthesia oral' 'pyrexia'
 'weight decreased' 'anaphylactic reaction' 'skin tightness'
 'skin laceration' 'stomach discomfort' 'constipation'
 'disturbance in attention' 'scar' 'swelling face' 'pharyngitis'
 'glossodynia' 'oral discomfort' 'physical examination' 'pneumonia'
 'panic attack' 'sensory loss' 'hair disorder' 'skin lesion'
 'muscle spasms' 'lethargy' 'acne' 'cerebrovascular accident'
 'paraesthesia oral' 'heart rate irregular' 'burning mouth syndrome'
 'body temperature abnormal' 'nervousness' 'dental caries' 'haematemesis'
 'back pain' 'limb injury' 'abdominal pain lower' 'balance disorder'
 'hospitalisation' 'dehydration' 'ingrown hair' 'sinus disorder' 'rigors'
 'impaired work ability' 'haematocrit increased' 'apparent death'
 'respiratory disorder' 'emergency care examination' 'fluid retention'
 'weight increased' 'respiratory tract congestion' 'alopecia' 'aphonia'
 'respiratory distress' 'parosmia' 'stomatitis' 'tongue coated'
 'epistaxis' 'eye irritation' 'appetite disorder' 'infection' 'wheezing'
 'renal failure chronic' 'tonsillar hypertrophy'
 'hepatic enzyme increased' 'menstrual disorder' 'renal disorder'
 'spinal pain' 'gastritis' 'tooth discolouration' 'toothache'
 'joint stiffness' 'fracture' 'foreign body' 'nasopharyngitis' 'neck pain'
 'depressed level of consciousness' 'visual impairment' 'productive cough'
 'throat tightness' 'hypothalamo-pituitary disorder' 'gait abnormal'
 'ischaemic stroke' 'loss of consciousness' 'diarrhoea haemorrhagic'
 'listeriosis' 'seizure' 'oral disorder' 'tachycardia' 'confusional state'
 'eye pain' 'hypersomnia' 'foreign body trauma' 'escherichia infection'
 'amnesia' 'laceration' 'choking' 'renal pain' 'oedema mouth'
 'localised oedema' 'diplopia' 'lip swelling' 'rash generalised'
 'renal impairment' 'muscular weakness' 'irritable bowel syndrome'
 'bladder disorder' 'change of bowel habit' 'cystitis'
 'urinary tract infection' 'viral test positive' 'jaundice' 'haemoptysis'
 'skin discolouration' 'anaphylactic shock' 'heart rate abnormal'
 'thermal burn']
Age: ['17' '8' '52' '4' '44' '33' '20' '23' '59' '70' '43' '46' '2' '12' '72'
 '29' '17.9' '60' '16' '57' '36' '3' '7' '46.38' '54' '65' '38' '30.92'
 '74' '35' '44.5' '41' '68' '53' '67' '47' '51' '40' '58' '61.69' '32.77'
 '11' '84' '28' '31' '24.6' '6' '27' '64' '69' '5' '24' '37' '61' '32'
 '34' '46.5' '18' '73' '25' '13' '14' '65.4' '45' '9' '1' '29.68' '71'
 '42' '68.3' '62' '42.1' '90' '49' '55' '30' '42.2' '26' '22' '50' '49.2'
 '76' '48' '56' '44.58' '39' '35.55' '63' '87' '15' '78' '24.67' '72.01'
 '80' '26.04' '21' '77' '48.21' '38.7' '33.5' '40.18' '49.65' '56.2'
 '34.1' '49.15' '47.6' '26.3' '18.1' '50.9' '19' '70.99' '42.9' '51.41'
 '32.9' '75' '66' '41.43' '82' '54.6' '45.4' '58.3' '89' '29.7' '38.51'
 '43.6' '38.4' '25.6' '41.55' '27.8' '51.2' '26.4' '10' '2.5' '6.85'
 '38.2' '38.9' '50.81' '46.9' '26.7' '3.02' '61.8' '25.8' '62.1' '12.92'
 '24.96' '65.2' '49.37' '50.82' '52.9' '26.64' '28.4' '32.8' '20.05'
 '74.6' '50.6' '54.5' '61.2' '38.3' '52.8' '67.18' '85' '35.68' '5.8'
 '59.61' '13.9' '63.5' '54.37' '35.96' '36.23' '47.58']
Gender: ['Female' 'Male' 'Unknown' 'Not Reported']
Product Name Brand: ['diet coke soda' 'archer farms market xl cooler, orange pineapple'
 'sobe lean diet mango melon beverage' 'acadia spring water' 'mt. dew'
 'aquafina bottled water' 'dr. pepper' 'avitae water'
 'gatorade  blackberry wave' 'flavored hydrolyzed protein wate'
 'poland springs natural spring water' 'bai water' 'diet coke'
 'nursery purified water'
 "marley's mellow mood citrus flavored sparkling relaxation drink"
 'food club spring water' 'arizona ice tea' 'squirt soda'
 'gatorade fierce bold and intense thirst quencher blue cherry'
 'nestle pure life purified water' 'fiji bottled water'
 'poland spring spring water' 'diet pepsi' 'schweppes ginger ale'
 'members mark bottled water' 'diet coke with caffeine' 'exemption 4'
 'red bull' 'arrowhead 100% mountain spring water'
 'nestle deer park sparkling mandarin water' 'diet coca-cola'
 'controlled labs orange traid daily multivitamin' 'diet dr. pepper'
 'southern california mountain ice'
 'gatorade recover o3 (lemon-lime-orange flavor)'
 'great value sodium free drinking water' 'great value spring water'
 'pepsico products' 'bawls guarana root beer'
 'zephyrhillis 100% natural florida spring water'
 'phd probiotic health daily, flavored water' 'now l-tryptophan'
 'pepsi cola' 'mio sweet tea' 'goslings ginger beer'
 'c-4 strawberry lemonade energy drink'
 'crystal light raspberry drink mix' 'mountain dew'
 'nursery purified water (steam distillation)' 'gatorade propel'
 'coke diet-coke' 'poland springs bottled water'
 'acadia natural spring water' 'diet schweppes tonic water'
 'propel fitness water' 'deer park water' 'diet cherry pepsi'
 'enfamil nutramigen' 'clutch energy cranberry apple revive energy drink'
 "sam's purified water with enhancing minerals"
 'nestle splash flavored water' 'minute maid fruit punch'
 'eternal naturally alkaline spring water' 'refreshe spring water'
 'dr. peper sprite zero' 'rockstar energy drink'
 'target brand fruit punch juice' 'perrier mineral water'
 'diet pepsi cola' 'sprite lemon lime soda'
 'kraft kool-aid jammers cherry' 'hony boy canned pink salmon in water'
 'one coconut water' 'vita coco' 'ice cream' 'fiji natural artesian water'
 'crystal light juice' 'redbull' 'burn energy drink'
 'dasani spring water lemon flavored' 'ssips fruit punch'
 'zip fizz liquid shot energy drink' 'coca cola diet coke'
 'crystal springs water' 'sprite lemon lime'
 'great value purified drinking water' 'arrowhead water' 'nitro pepsi'
 'crystal springs mountain spring bottled water' 'giordanos juice'
 'flow organic lemon ginger alkaline spring water'
 'mountainwood springs (labeled diamond rock)  spring water' 'coca cola'
 'simply lemonade with raspberry' 'pepsi cola soft drink'
 'pure american spring water' 'red bull sugar free'
 'bai cocofusions molokai coconut antioxidant infused'
 'v8 vegetable juice' 'diet drinks' 'airway clear'
 'arrowhead mountain spring water' 'mitra kratom seltzer'
 'hawaiian punch fruit juicy red' 'shark energy drink'
 'amped hydrate juicy orange' 'kentwood springs distilled water'
 'gatorade rain sports non-carbonated drink' 'ozarka spring water'
 'poland spring 100% spring water' 'prime lemonade'
 'just the basics strawberry lemonade'
 'poppi strawberry lemon prebiotic soda' "hal's new york coffee seltzer"
 'fyxx hybrid caffeinated spring water' 'market pantry water' 'nos energy'
 'red bull the red edition' 'gatorade lemon lime thirst quencher'
 'aquafina' 'coca cola coca cola classic' 'ozarka  proudly texan'
 'market pantry purified drinking water, enhanced with minerals for taste'
 'soda kola champagne' 'monster energy green' 'le croix grapefruit'
 'bottle of poland springs water' 'dasani bottled water'
 'kool-aid sugar free water enhancer' 'triple cola'
 'essential everyday distilled water' 'ozarka bottled water'
 'super ice pure &amp; clean (kroger) ice cubes' 'pepsi co diet pepsi 24 pack'
 'little rainbow blue raspberry drink' 'coke zero'
 'kirkland signature 2% milk' 'wild cherry pepsi' 'full throttle'
 'aquafina flavored water' 'care pharmaceuticals haydralyte'
 'members mark purified water' '7 up' 'ale 8 1 soft drink opaque ale 8 1'
 'vua kho bo xi muoi' 'monster energy drink' 'pepsi bottled soda'
 'coca cola classic' 'gatorade frost drink' 'snapple apple juice drink'
 'rainbow rainbow blue raspberry drink' 'gatorade' 'pepsi regular pepsi'
 'urban moonshine immune zoom' 'powerade power water'
 'coca cola caffeine free cola' 'mountain mist natural sxpring water'
 'zico coconut water' 'le bleu water' 'slammers trix' 'smart water'
 'pepperidge farm brownsugar cinnamon mini bagels'
 'western family bottled spring water'
 'bai flavored water oasis variety pack antioxident infused' 'sprite'
 'la croix coconut' 'a-ha sparkling water' "le nature's ice water"
 'sobe lifewater strawberry dragonfruit' 'snapple diet raspberry'
 'general mills fiber one' 'coca-cola fuze green tea'
 'diamond falls pure granulated sugar' 'truestar supershot'
 'monster energy' 'deer park 100 % natural spring water'
 'great bear natural spring water' 'bonaqua flavored mineral water'
 'red bull watermelon sugar free' 'dr. pepper carbonated soft drink'
 'dasani purified water' 'devacurl decadance conditioner'
 'market pantry punch flavored 100% juice' 'shasta cola'
 "teddy's old fashioned creme soda" 'nabisco premium saltine crackers'
 'black cherry mitra-9 kratom seltzer'
 'arizona rocket fuel extreme energy drink' 'fiji artesanal water'
 "ryan's apple cider 100% juice" 'food lion water purified'
 'bubly sparkling water coconut pineapple flavor'
 'mountain dew code red (pepsico) carbonated soft drink' 'c4 energy'
 'malta goya' 'ace energy drink' 'minute maid peach punch'
 'le marche francais sparkling blood orange flavored drink'
 'alo twist aloe vera juice drink' 'kirkland signature sparkling water'
 'olipop classic root beer' 'power aide mountain berry blast'
 'distilled water' 'vita coco coconut water the original'
 'poland springs bottle water' 'diet rite' 'dr. zevia zero calorie soda'
 'grape naturally flavored zevia zero calorie soda' 'sunny d'
 "trader joe's natural mountain spring water"
 'sobe lifewater enlighten - blackberry grape' '7-eleven bottle water'
 'crystal light' 'absopure purified drinking water'
 'mistic sparkling lime kiwi water' 'dr pepper' 'coca-cola diet coke'
 'poland spring/100% natural spring water' 'diet mountain dew'
 "uncle ben's long grain &amp; wild rice" 'zephyrhills water'
 'evian bottled water' 'a&amp;w root beer' 'water'
 'enfamil nutramigen aa (prescription powdered formula)'
 'quaker gatorade punch' 'mountaintop extracts tiki juice thc'
 'nestle pure life' 'sparkletts bottled water' 'adam and eve fruit punch'
 'coca cola original' 'gatorade g2 orange drink' 'winn dixie v-h2o'
 "canfield's lemon natural flavor seltzer water"
 'pillsbury sugar free cinnamon rolls'
 'monster beverage co monster energy'
 'crystal geyser plastic bottled water' 'dr. pepper 10. aspartame'
 'crystal light diet drink' 'diamond creek spring water'
 'naked green machine boosted 100% juice smoothie' 'orange powerade'
 'crystal geyser natural alpine spring water'
 'minute maid premium tropical punch' 'diet coca cola'
 'food lion seltzer water raspberry water'
 'food lion sparking water peach flavor'
 'herbalife 21 day herbal cleansing program' 'vitamin water power c'
 'fentimans dandelion and burdock soda' 'eternal bottled spring water'
 'safeway refreshe lemon lime soda' 'quinine tonic water'
 'chi sparkling water white peach' 'mns max c (maximum appetite control)'
 'full throttle energy drink' 'hawaiian lemon berry fruit punch'
 'x mode energy drink'
 'great value purified drinking water with flavor-enhancing minerals'
 'perrier sparkling natural mineral water' 'gatorade low calone g2 orange'
 'sunny-d sunny delight tangy original florida style original sport bottle'
 'essentia 9.5ph' 'minute maid raspberry lemonade' 'gatorade lemon lime'
 'talking rain beverage' 'bai andes coconut lime drink'
 '7up zero sugar lemon lime' 'ningxia zyng'
 'tops thirst quencher (orange flavor)' 'best choice bottled water'
 'pepsi cola diet pepsi wild cherry' 'sqwincher fruit punch'
 'niagara bottled water'
 'ice mountain natural spring water with added fluoride kid safe cap'
 'pepsi' 'rockstar perfect berry zero sugar zero carbs energy drink'
 'jif peanut butter' 'cheese' "trader joe's natural spring water"
 'caribbean hibiscus sorrell wine' 'real water alkaline water'
 'trimino protein infused water coconut pineapple'
 'kevitas probiotic drinks with stevia' 'kraft lunchable'
 'real water alkalized water' 'vintage seltzer'
 'diet pepsi cola flavored, carbonated soft drink'
 'bubly sparkling water blackberry bubly' 'monster energy drink rehab'
 'crystal geyser spring water' 'gerber pure waterfor infants'
 'starbucks double shot'
 'energy brands inc. full throttle citrus 12 fl oz'
 'nestle pure life water'
 'simple truth organic seltzer water orange vanilla' 'pathmark spinach'
 'propel fit water' 'pure delite fruit punch' 'strawberry vanilla olipop'
 'monster energy ultra blue' 'mega food baby &amp; me 2 pre &amp; post natal'
 'bargs diet root beer' 'shasta diet cola'
 'gatorade x factor lemon lime with strawberry'
 'fruity king  mini soda pineapple' 'v8 v-sparking fusion' 'real waters'
 'gatorade thirst quencher orange' 'penta water' 'klondike'
 'essentia purified bottled water' 'coca-cola life' 'coca cola dr. pepper'
 'propel single serving packets' 'essentia water'
 'wegmans strawberry apple juice'
 'full throttle original citrus energy drink' 'white rock ginger ale'
 'fanta grape' 'irn bru drink' 'crystal geyser bottled water' 'coca-cola'
 'dr. pepper caffeine free' 'coca cola full throttle energy drink'
 'schweppes ginger ale, 10 oz.'
 'mead johnson enfamil lipil with iron powder'
 'snapple beverage co. diet snapple' 'coca-cola coke'
 'coca-cola feisty cherry diet coke'
 'sparkling ice coconut pineapple carbonated water' 'daily harvest food'
 'niagara purified drinking water' 'deja blue bottled water'
 'sobe lifewater' 'gatorade g2  orange drink'
 'san pellegrino mineral water' 'pure water' 'gerber nursery water'
 'arrowhead premium ice' '7 selected chocolate milk vitamin d'
 'liquid i.v. hydration multiplier electrolyte drink mix firecracker'
 'minute maid (coca cola) all natural coolers pink lemonade'
 'loca mocha java monster'
 'hydroxycut pro clinical caplets (dietary supplement) caplet'
 'fizz bizz soda' 'karma probiotic water' 'vasa natural spring water'
 'olaplex no 3 repair protector' 'tartrazine, yellow #5'
 'sams minnie lemon lime soda' 'coke soft drinks'
 'zephyrhills natural spring water' 'guaranteed value cola soda'
 'botanical brewing company delta-9 lemon pound cake euphoric and chill'
 'snapple half and half lemonade iced tea' 'red bull energy drink'
 'minute maid concentrated orange juice' 'monster energy vr46'
 'kirkland signature purified water' 'crystal geyser water'
 'sunkist orange soda' 'seven up soda with calcium and vitamin'
 'odwalla super food green drink' 'real water'
 'thunderhead wild blackberry fruit flavored pure water beverage'
 'capri sun fruit punch juice'
 'powerade ion4 advanced electrolyte system sports drink with vitamins b3 b6 and b12 grape flavored'
 'stars and stripes cola'
 's.pellegrino sparkling natural mineral water, plastic bottles'
 'jif creamy peanut butter' 'perrier carbonated mineral water'
 'gatorade rain forest' 'coca cola move' 'unspecified energy drink'
 'ice water' 'acutrim natural a.m'
 'berry cool artificial fruit flavored soft drink'
 'sparkling ice cherry limeade' 'great value purified water'
 'alhambra water' 'planters pistachio lovers mix'
 'capri sun fruit punch flavor juice' 'minute maid light lemonade'
 'nitro pepsi vanilla draft cola' 'glaceau vitamin water'
 'motts active blastin berry hydrating juice beverage'
 'powerade sports drink' 'cub foods natural spring water'
 'sierra mist lemon lime soda'
 'haelan products fermented high concentrated soy beverage'
 'lo-carb and zero sugar monster energy drinks'
 'clover valley lemon lime flavored sparkling water'
 'primo sparkletts water' 'gatorade recover 03' 'dasani water bottle'
 'naked protein banana chocolate juice smoothie' 'cranberry lime seltzer'
 'cortislim' 'amelia electrolyte water' 'puraqua'
 'talking rain lemon lime sparking spring water' 'diet dr.pepper'
 'diet rock star' 'bug juice berry raspberry drink'
 'jumex fruta de mi tierra guava nectar from concentrate juicy guavas'
 'the plug drink' 'capri sun water' 'aspartame' 'diet rite cherry cola'
 'gatorade performance 02 g series orange' 'gerber pure purified water'
 'capri sun juice drink blend fruit punch' 'monster energy zero ultra'
 'great value drinking water' 'fiji water  natural artesian'
 'isalean shake - creamy dutch chocolate' 'poland springs spring water'
 '365 everyday value organic unsweetened coconut original coconut milk beverage'
 'nestle waters san pellegrino mineral water'
 'crystal geyser natural alpine spring bottled water'
 'arizona rx energy herbal tonic' 'lost energy drink'
 'deer park spring water bottled' 'cocacola'
 'coca~cola classic carbonated cola flavored soft drink'
 'san pellegrino sparkling mineral water' 'soda' 'puraqua purified water'
 'mug rootbeer' 'tropicana fruit punch' 'artificial flavors colors'
 'ice mountain bottled water' 'tang' 'meal replacement shake - vanilla'
 'white rock sioux city cream soda' 'dasani water'
 'zero sugar summer splash punch'
 'genesistoday plant-based probiotic dietary supplement' 'diet soda'
 'rain berry flavor gatorade' 'iberia 100% pure coconut water'
 'botonic tonic feel free tonic' 'deer park natural spring water'
 'deer park bottled water' 'poland springs original sparkling water'
 'sparkling ice' 'crystal spring water water,nursery fluorodated'
 'coca-cola cherry' 'glaceau smart water'
 'wawa mixed berry enhanced water'
 'caprisun strawberry kiwi flavored juice drink blend'
 'earthbound farm organic 50/50 spinach and spring mix' 'aloe vera fresh'
 'kirkland water bottles' 'pure life water' 'fiji water'
 'capri sun fruit punch' 'broccoli crowns'
 'nestles deer park bottled water' 'bai antioxidant infusion'
 'kroger purified drinking water' 'gatorade twitch cool blue'
 'vernors carbonated drink' 'nestle splash' 'yoo-hoo'
 'united airlines food dinner chicken with red sauce and noodles with sides of bread &amp; butter and rice'
 'daily harvest mixed meals'
 'bolthouse farms green goodness 100% juice smoothie'
 'diet drinks containing aspartame' 'canada dry tonic water with quinine'
 'now gaba' 'vernors ginger ale'
 'artificial sweetener mountain dew diet drink' 'olipop cream soda'
 'dasani enhanced mineral water' 'mega monster energy' 'avitae'
 'igreeen soy steak jerky' 'pepsi max diet pepsi'
 'hill country fare red ruby grapefruit cocktail blend from concentrate'
 'powerade lemon lime powerade' 'gfuel energy drink' 'rush'
 'monster energy absolutely zero' 'cordymax' 'kroger bottled water'
 'diet sierra mist carbonated, citrus flavored soft drink'
 'coca cola coke'
 "kids and us food based mini's, vitamin, mineral and herbal supplement"
 'gatorade thirst quencher' 'glaceau xxx flavored vitamin water'
 'c4 sugar free energy drinks' 'bolthouse farms protein plus chocolate'
 'rite aide big fizz cola' 'aquafina water'
 'artesian fusion natural mineral water'
 'monster energy drink - mixed flavors' 'bang energy drink'
 'detoxing juice' 'snapple fruit punch' 'aloe vita zero white grape water'
 'earth h2o bottled water' 'krazykritter vitamin drink apple gator'
 'capri sun orange drink' 'bodyarmor lyte dragonfruit berry' "sam's cola"
 'pepsi-cola mountain dew' 'gatorade g2'
 'hydroxycut hardcore rapid release capsules (dietary supplement) capsules'
 'faygo orange faygo soda' 'safeway refresh purified drinking water'
 'gridlock energy drink 20 mg cott beverage'
 'poland spring 100% natural spring water' 'cellucor super hd'
 'celestial seasonings white tea' 'poland springs bottled spring water'
 'innovasion vegetable fried rice' 'primo water' 'pure coconut water'
 'cocain energy drink' 'avitae natural caffeinated unflavored water'
 'clear american wild cherry'
 'simple truth organic mixed fruit medley strawberries, peaches, pineapple'
 'fuze slenderize drink with citramax 200mg' 'centrum silver'
 'clean yerba mate' 'poland springs water spring water, bottled'
 'sobe life water' 'sobe power fruit punch'
 'sunny delight citrus punch orange flavored drink'
 'premium waters chippewa spring water 32 .5 liter bottles'
 'pepsi pepsi max zero calorie carbonated soft drink' 'reddy ice'
 "member's mark purified water mineral enhanced for taste"
 'diet coke aspartame' 'dr. pepper 7 up squirt soda'
 'harris teeter raspberry lime flavored seltzer'
 's. pelligrino sparkling natural mineral water'
 'canada dry diet ginger ale' 'caffeine free diet pepsi'
 'the original d8 seltzer' 'aquafina purified bottled water' 'rc cola'
 'poland bottled spring water'
 'puraqua belle vie lime sparkling water 12 ounce can'
 'clover valley purified drinking water eco air bottle'
 'sprite fountain drink' 'coca-cola diet coke with lime'
 'core hydration water' 'arrowhead sparkling water'
 'kirkland powdered infant formula' 'spring natural water'
 'sunny delight sunny delight' 'pepsi-co sierra mist'
 'mexican-style caesar salad bowl' 'kentwood spring water'
 'poland spring water' 'fuze beverage tangerine grapefruit'
 'capri sun mixed fruit flavor' 'capri sun orignal, fruit punch'
 'crystal geyser sparkling mineral water original'
 'hemp extract seltzer-8' 'jewell infant drinking water'
 'delmonte pineapple juice' 'monster energy gronk'
 'botanical brewing company delta-8 passionfruit mojito elevate + unwind'
 'rc diet rc' 'coca-cola full throttle' 'big k diet caffeine free cola'
 'circle k blue  raspberry soda' 'hi ball energy grapefruit'
 "kicker's energy spray" 'stur liquid water enhancer'
 'quick loss diet spray with hoodia' 'tap water' 'silver falls water'
 'parents choice distilled water' 'absopure natural spring water'
 'sobe smooth pepsico orange cream soft drink'
 '5-hour energy berry regular strength' 're2al water'
 'kozy shack original recipe rice pudding gluten free' '7up diet soda'
 'poland springs sports bottled water' 'naked mango smoothie'
 'kraft foods capri sun pacific cooler' 'dry lavender soda'
 "nature's nectar 100% pure coconut water tropical hydration"
 'dr. thunder' '7-up 10' 'capri sun'
 'canada dry ginger ale naturally sweetened with stevia'
 'mountain dew soft drink citrus flavor' 'gatorade flow tidal punch'
 'fiji artesian water' 'spring valley beta carotene 25000 iu'
 'gatorade g2 fruit punch'
 'flow organic lemon giner alkaline spring water' 'fanta strawberry'
 'mountain dew zero' 'sierra mist' 'calcium mineral water'
 'gatorade glacier frost freeze' 'monster energy drink loca moca'
 'protein20 infused protein water' 'gatorade zero lemon lime'
 'g2 gatorade' 'rip it' 'lifeline water'
 'twenty-four pack dasani purified bottle water'
 'ice mountain spring water' 'goya malta' 'enfamil ar' 'smartwater'
 'lifesavers' 'coca cola spiced raspberry spiced coke' 'fanta orange'
 'pepsi soda' 'vitamin water zero calories' 'crush cherry flavor beverage'
 'gatorade g series thirst quencher performance 02 cool blue'
 'arizona diet green iced tea' 'sprouts baby food pouch' 'la croix curate'
 'feisty cherry diet coke' "trader joe's organic baby spinach"
 'cola shasta shasta cola twelve pack' "sam's club purified water"
 'rc cola, soft drink' 'act ii kettle corn' 'sprite zero soft drink soda'
 'hi-c orange drink' 'walgreens bag of ice' 'rockstar punched'
 'golden gate soy bean drink' 'aquafina purified drinking bottled water'
 'purified water with minerals added for taste'
 'ashoc accelerated cherry limade'
 'thurst burst orange artificially flavored non-carbonated drink'
 'cherry coca cola energy' 'jamba juice smoothie' 'coke'
 'sobe life water, pomegranate cherry' 'canada dry club soda'
 'scott county virginia tap water'
 'abbott similac advance optigrow powdered infant formula' 'coors light'
 'kratom drink' 'shoprite miniature water' 'simply light lemonade'
 'fox ledge distilled water gallon' 'essentia  h2o ionized hydration'
 'polar blast hawaiian punch' 'canada dry ginger ale soft drink'
 'gatorade series prime perform 01,02,03 lemon lime drink'
 'diet coca cola soda' 'nos high performance energy drink'
 'cherry coca-cola' 'krampade 2k' 'sabra hummus small dipper'
 'nusery purified water' 'aquafina bottle water'
 'glaceau vitamin water zero squeezed lemonade flavor'
 "kirkland's signature tilapia, fresh frozen fillets"
 'mounsier papa soursop nectar' 'absopure all natural spring water'
 'clover valley dr topper' 'brain &amp; memory power boost'
 'revive superfoods mango &amp; pineapple smoothie'
 'stars and stripes cola soda' 'zephyr hills water'
 'monster rehab tea+lemonade+energy' 'shasta sparkling club soda'
 'chocolate candy coin' 'farms premium drinking' 'gatorades'
 'juicy juice fruit punch' 'kirkland water'
 'rainsberry farms rainberry fruit punch'
 "america's choice bottled spring water"
 'fred meyer purified drinking water' 'minute maid orange juice'
 'power aide option strawberry flavored low calorie sports drink'
 'roxanne bottled water' 'bai antioxidant water'
 'runa clean energy drink unsweetened watermelon'
 'sparkling ice coconut pineapple flavored sparkling water' 'coffee'
 'pellegrino essenza' 'belly washers spider man 100% juice fruit punch'
 'dr. pepper squirt soda' 'spendrift sparkling water grapefruit'
 'monster energy mega drink' 'clovervalley purified drinking water'
 'coca cola classic cola' 'vintage sheltzer lemon lime'
 'honest tea peach oyo-la-long tea' 'nitro energy drinks'
 'tejava unsweetened iced tea' 'diet sundrop' 'ginger ale'
 'mio fruit punch' 'arizona sweetened tea' 'rockstar punched energy drink'
 'pepsi cola soda' 'zephyrhills florida spring water' 'dr pepper soda'
 'arnold palmer lite' 'gatorade fruit punch'
 'great value purified drinking water with flavor &amp; enhancing minerals'
 'diamond crystal potassium chloride salt substitute'
 'tropicana orangeade sugar' 'coca-cola blak'
 'infant water - purified water with minerals added for taste'
 'pepsi cola, regular' 'quaker big chewy chocolate chip' '7-up'
 'canada dry tonic water' 'kemps grape drink'
 'brisk drinks half &amp; half ice tea and lemonade' 'organic mamma chia'
 'rockstar punched energy drink - hardcore apple' "diet soda's"
 'monster nervy drink' 'enfamil gentlease formula'
 'vita coco coconut water' 'schweppes gingerale soda'
 'arizona sweet tea southern style real brewed'
 'coca cola classic carbonated cola flavored soft drink'
 'propel propel (grape flavored)' 'on the house pina colada cocktail mix'
 'good &amp; gather purified drinking water' 'kho bo vietnamese drinks'
 'mountain dew voltage soda'
 'perrier (nestle) lemon lime flavored mineral water'
 'gatorade frost thirst quencher'
 'batman fruit drink cheeky cherry belly washer drink'
 'hinckley springs natural spring water' 'frugal malt' 'pepsi mango'
 'rehab tea+lemonade 15.5 oz' 'fuze healthy infusions beverage'
 "hi-c flashin' fruit punch"
 'glaceau vitamin water - acai blueberry pomegranate' "campbell's soup"
 'kirkland signature bottled spring water'
 'glaceau vitaminwater xxx acai blueberry pomegranate flavor'
 "sam's choice purified drinking water" 'vess cola'
 'powerade lemon lime flavor'
 'gatorade tangerine mandering g thirst quencher' 'real water water'
 'rebel rabbit cannabis-infused seltzers' 'speed stack sports drink'
 'ice canyon natural spring water' 'diet rite cola'
 'chocolate naked nutrition grass-fed whey + raw cacao = coconut sugar with nothing to hide'
 'diet coke with nutrasweet' 'diet canada dry' 'ice mountain water'
 'gatorade thirst quencher, orange' 'michael ochoa cbd water']</code></pre>
</div>
</div>
<div id="cell-11" class="cell" data-outputid="5d188227-bc59-42b6-b5c4-573e7677b067">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#df['age'] = df['age'].astype(int)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#np.mean(df['age'])</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#set(df['age'])</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'age'</span>] <span class="op">=</span> pd.to_numeric(df[<span class="st">'age'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>np.mean(df[<span class="st">'age'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="75">
<pre><code>38.42354901960785</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1><strong>Exploratory Data Analysis:</strong></h1>
<p>We now expore the dataset by: * Generate summary statistics and descriptive insights * Visualize distributions, relationships, and trends * Identify patterns, correlations, and anomalies * Provide initial interpretations of data insights</p>
<div id="cell-14" class="cell" data-outputid="470f0b16-ab5f-404e-d38a-4df975d8487f">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>dummy_col <span class="op">=</span> df.columns[df.columns.<span class="bu">str</span>.startswith(<span class="st">"reaction_"</span>)].tolist()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>dummy_col.extend(df.columns[df.columns.<span class="bu">str</span>.startswith(<span class="st">"outcome_"</span>)].tolist())</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dummy_col)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> df:</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> i <span class="kw">in</span> dummy_col:</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    df[i] <span class="op">=</span> df[i].astype(<span class="bu">int</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['reaction_abasia', 'reaction_abdominal discomfort', 'reaction_abdominal distension', 'reaction_abdominal hernia', 'reaction_abdominal pain', 'reaction_abdominal pain lower', 'reaction_abdominal pain upper', 'reaction_abdominal tenderness', 'reaction_abnormal behaviour', 'reaction_accidental exposure to product', 'reaction_acne', 'reaction_acute myocardial infarction', 'reaction_adverse event', 'reaction_adverse reaction', 'reaction_aeromonas test positive', 'reaction_ageusia', 'reaction_agitation', 'reaction_alopecia', 'reaction_amnesia', 'reaction_amyotrophic lateral sclerosis', 'reaction_anaemia', 'reaction_anaphylactic reaction', 'reaction_anaphylactic shock', 'reaction_anger', 'reaction_anorexia', 'reaction_anosmia', 'reaction_anxiety', 'reaction_aphonia', 'reaction_aphthous stomatitis', 'reaction_apparent death', 'reaction_appetite disorder', 'reaction_arrhythmia', 'reaction_arthralgia', 'reaction_asthenia', 'reaction_asthma', 'reaction_atelectasis', 'reaction_atrial fibrillation', 'reaction_atrial flutter', 'reaction_back injury', 'reaction_back pain', 'reaction_bacteria stool identified', 'reaction_bacterial infection', 'reaction_bacterial test positive', 'reaction_balance disorder', 'reaction_bipolar i disorder', 'reaction_bladder disorder', 'reaction_blindness unilateral', 'reaction_blister', 'reaction_blood cholesterol increased', 'reaction_blood creatine phosphokinase increased', 'reaction_blood glucose abnormal', 'reaction_blood glucose decreased', 'reaction_blood glucose increased', 'reaction_blood lactic acid increased', 'reaction_blood pressure decreased', 'reaction_blood pressure fluctuation', 'reaction_blood pressure increased', 'reaction_blood testosterone increased', 'reaction_blood urine present', 'reaction_body temperature abnormal', 'reaction_body temperature increased', 'reaction_bone pain', 'reaction_brain abscess', 'reaction_brain injury', 'reaction_breast discharge', 'reaction_bruxism', 'reaction_burn oesophageal', 'reaction_burning mouth syndrome', 'reaction_burning sensation', 'reaction_burning sensation mucosal', 'reaction_candidiasis', 'reaction_cardiac arrest', 'reaction_cardiac fibrillation', 'reaction_cardiac murmur', 'reaction_cardiopulmonary failure', 'reaction_cardioversion', 'reaction_caustic injury', 'reaction_cerebrovascular accident', 'reaction_change of bowel habit', 'reaction_chemical burn', 'reaction_chemical burn of respiratory tract', 'reaction_chemical injury', 'reaction_chest discomfort', 'reaction_chest pain', 'reaction_chills', 'reaction_choking', 'reaction_choking sensation', 'reaction_chromaturia', 'reaction_circumoral oedema', 'reaction_clostridium test positive', 'reaction_cognitive disorder', 'reaction_cold sweat', 'reaction_colitis', 'reaction_computerised tomogram abnormal', 'reaction_condition aggravated', 'reaction_confusional state', 'reaction_conjunctivitis allergic', 'reaction_constipation', 'reaction_contusion', 'reaction_convulsion', 'reaction_corneal laceration', 'reaction_corona virus infection', 'reaction_cough', 'reaction_cronobacter infection', 'reaction_crying', 'reaction_culture stool positive', 'reaction_cystitis', 'reaction_dark circles under eyes', 'reaction_deafness', 'reaction_death', 'reaction_decreased appetite', 'reaction_decreased immune responsiveness', 'reaction_dehydration', 'reaction_delirium', 'reaction_demyelination', 'reaction_dental caries', 'reaction_dependence', 'reaction_depressed level of consciousness', 'reaction_depressed mood', 'reaction_depression', 'reaction_diabetes insipidus', 'reaction_diabetes mellitus non-insulin-dependent', 'reaction_diarrhoea', 'reaction_diarrhoea haemorrhagic', 'reaction_difficulty in walking', 'reaction_diplopia', 'reaction_discomfort', 'reaction_disorientation', 'reaction_disturbance in attention', 'reaction_dizziness', 'reaction_drug interaction', 'reaction_drug toxicity', 'reaction_dry eye', 'reaction_dry mouth', 'reaction_dry skin', 'reaction_dry throat', 'reaction_dysarthria', 'reaction_dysentery', 'reaction_dysgeusia', 'reaction_dyskinesia', 'reaction_dyspepsia', 'reaction_dysphagia', 'reaction_dysphonia', 'reaction_dyspnoea', 'reaction_dysuria', 'reaction_ear', 'reaction_ear infection', 'reaction_ear injury', 'reaction_electrocardiogram', 'reaction_electrocardiogram abnormal', 'reaction_emergency care examination', 'reaction_emotional distress', 'reaction_epistaxis', 'reaction_eructation', 'reaction_erythema', 'reaction_erythromelalgia', 'reaction_escherichia infection', 'reaction_euphoric mood', 'reaction_excoriation', 'reaction_exophthalmos', 'reaction_extrasystoles', 'reaction_eye disorder', 'reaction_eye infection', 'reaction_eye inflammation', 'reaction_eye injury', 'reaction_eye irritation', 'reaction_eye pain', 'reaction_eye pruritus', 'reaction_eye swelling', 'reaction_face oedema', 'reaction_factitious disorder', 'reaction_faecal incontinence', 'reaction_faeces discoloured', 'reaction_fall', 'reaction_fatigue', 'reaction_feeling abnormal', 'reaction_feeling hot', 'reaction_feeling jittery', 'reaction_feeling of body temperature change', 'reaction_flatulence', 'reaction_fluid retention', 'reaction_flushing', 'reaction_food craving', 'reaction_food poisoning', 'reaction_foreign body', 'reaction_foreign body trauma', 'reaction_fracture', 'reaction_fructose intolerance', 'reaction_gait abnormal', 'reaction_gait disturbance', 'reaction_gastric disorder', 'reaction_gastritis', 'reaction_gastroenteritis', 'reaction_gastroenteritis aeromonas', 'reaction_gastroenteritis salmonella', 'reaction_gastroenteritis viral', 'reaction_gastrointestinal bacterial infection', 'reaction_gastrointestinal discomfort', 'reaction_gastrointestinal disorder', 'reaction_gastrointestinal haemorrhage', 'reaction_gastrointestinal infection', 'reaction_gastrointestinal pain', 'reaction_gastrointestinal sounds abnormal', 'reaction_gastrointestinal tract irritation', 'reaction_gastrooesophageal reflux disease', 'reaction_general physical health deterioration', 'reaction_gingival pain', 'reaction_glaucoma', 'reaction_glossodynia', 'reaction_grand mal convulsion', 'reaction_haematemesis', 'reaction_haematochezia', 'reaction_haematocrit increased', 'reaction_haemoptysis', 'reaction_haemorrhage', 'reaction_hair disorder', 'reaction_hallucination', 'reaction_headache', 'reaction_heart rate abnormal', 'reaction_heart rate increased', 'reaction_heart rate irregular', 'reaction_hepatic enzyme increased', 'reaction_hepatitis', 'reaction_hepatitis c', 'reaction_hepatocellular damage', 'reaction_hospitalisation', 'reaction_hot flush', 'reaction_hunger', 'reaction_hyperchlorhydria', 'reaction_hyperhidrosis', 'reaction_hypersensitivity', 'reaction_hypersomnia', 'reaction_hypertension', 'reaction_hypoaesthesia', 'reaction_hypoaesthesia oral', 'reaction_hypoglycaemia', 'reaction_hypothalamo-pituitary disorder', 'reaction_hypothyroidism', 'reaction_hypotrichosis', 'reaction_hypoventilation', 'reaction_illness', 'reaction_immune system disorder', 'reaction_impaired work ability', 'reaction_increased appetite', 'reaction_increased bronchial secretion', 'reaction_increased upper airway secretion', 'reaction_infection', 'reaction_inflammation', 'reaction_influenza', 'reaction_influenza like illness', 'reaction_ingrown hair', 'reaction_injury', 'reaction_injury corneal', 'reaction_insomnia', 'reaction_intestinal obstruction', 'reaction_irritable bowel syndrome', 'reaction_ischaemic stroke', 'reaction_jaundice', 'reaction_joint lock', 'reaction_joint stiffness', 'reaction_joint swelling', 'reaction_judgement impaired', 'reaction_klebsiella infection', 'reaction_laceration', 'reaction_lacrimation increased', 'reaction_laryngitis', 'reaction_learning disability', 'reaction_learning disorder', 'reaction_lethargy', 'reaction_leukocytosis', 'reaction_libido decreased', 'reaction_limb discomfort', 'reaction_limb injury', 'reaction_lip and/or oral cavity cancer', 'reaction_lip blister', 'reaction_lip swelling', 'reaction_listeriosis', 'reaction_liver function test abnormal', 'reaction_liver injury', 'reaction_local swelling', 'reaction_localised oedema', 'reaction_loose stools', 'reaction_loss of consciousness', 'reaction_lumbar puncture', 'reaction_lung infection', 'reaction_lung infiltration', 'reaction_lymphadenopathy', 'reaction_malaise', 'reaction_memory impairment', 'reaction_meningioma', 'reaction_menstrual discomfort', 'reaction_menstrual disorder', 'reaction_mental disorder', 'reaction_metabolic acidosis', 'reaction_metabolic disorder', 'reaction_migraine', 'reaction_mood altered', 'reaction_mood swings', 'reaction_motor dysfunction', 'reaction_mouth haemorrhage', 'reaction_mouth ulceration', 'reaction_mucous membrane disorder', 'reaction_multiple sclerosis', 'reaction_muscle atrophy', 'reaction_muscle fatigue', 'reaction_muscle spasms', 'reaction_muscle twitching', 'reaction_muscular weakness', 'reaction_musculoskeletal discomfort', 'reaction_musculoskeletal disorder', 'reaction_musculoskeletal stiffness', 'reaction_myalgia', 'reaction_mydriasis', 'reaction_myocardial infarction', 'reaction_nail discolouration', 'reaction_nasal congestion', 'reaction_nasopharyngitis', 'reaction_nausea', 'reaction_neck pain', 'reaction_nerve block', 'reaction_nerve injury', 'reaction_nervous system disorder', 'reaction_nervousness', 'reaction_night sweats', 'reaction_nose and throat examination', 'reaction_obsessive-compulsive disorder', 'reaction_obstructive airways disorder', 'reaction_ocular hyperaemia', 'reaction_oedema', 'reaction_oedema mouth', 'reaction_oedema peripheral', 'reaction_oesophageal pain', 'reaction_oesophagitis', 'reaction_oesophagitis chemical', 'reaction_onychoclasis', 'reaction_onycholysis', 'reaction_optic nerve disorder', 'reaction_optic neuritis', 'reaction_oral discomfort', 'reaction_oral disorder', 'reaction_oral dysaesthesia', 'reaction_oral pain', 'reaction_oropharyngeal blistering', 'reaction_oropharyngeal pain', 'reaction_oropharyngeal swelling', 'reaction_orthostatic hypotension', 'reaction_osteoarthritis', 'reaction_osteogenesis imperfecta', 'reaction_overdose', 'reaction_pain', 'reaction_pain in extremity', 'reaction_pain in jaw', 'reaction_pallor', 'reaction_palpitations', 'reaction_pancreatitis', 'reaction_panic attack', 'reaction_paraesthesia', 'reaction_paraesthesia oral', 'reaction_paralysis', 'reaction_parosmia', 'reaction_peripheral sensory neuropathy', 'reaction_personality change', 'reaction_pharyngeal erythema', 'reaction_pharyngeal oedema', 'reaction_pharyngeal swelling', 'reaction_pharyngitis', 'reaction_pharyngitis streptococcal', 'reaction_pharyngolaryngeal pain', 'reaction_photophobia', 'reaction_physical examination', 'reaction_plantar fasciitis', 'reaction_platelet count increased', 'reaction_pleurisy', 'reaction_pneumonia', 'reaction_poisoning', 'reaction_pollakiuria', 'reaction_polydipsia', 'reaction_polyuria', 'reaction_product contamination', 'reaction_product contamination chemical', 'reaction_product contamination microbial', 'reaction_product contamination physical', 'reaction_product odour abnormal', 'reaction_product taste abnormal', 'reaction_productive cough', 'reaction_pruritus', 'reaction_pruritus generalised', 'reaction_psychomotor hyperactivity', 'reaction_pulmonary embolism', 'reaction_pyrexia', 'reaction_rash', 'reaction_rash generalised', 'reaction_rash papular', 'reaction_rash pruritic', 'reaction_regurgitation', 'reaction_renal disorder', 'reaction_renal failure', 'reaction_renal failure acute', 'reaction_renal failure chronic', 'reaction_renal impairment', 'reaction_renal pain', 'reaction_respiratory disorder', 'reaction_respiratory distress', 'reaction_respiratory tract congestion', 'reaction_restless legs syndrome', 'reaction_restlessness', 'reaction_resuscitation', 'reaction_retching', 'reaction_rhinorrhoea', 'reaction_rigors', 'reaction_rosacea', 'reaction_salivary gland disorder', 'reaction_salivary hypersecretion', 'reaction_salmonellosis', 'reaction_scar', 'reaction_seborrhoeic dermatitis', 'reaction_secretion discharge', 'reaction_seizure', 'reaction_sensory loss', 'reaction_sepsis', 'reaction_sexual dysfunction', 'reaction_shoulder pain', 'reaction_sinus disorder', 'reaction_sinusitis', 'reaction_skeletal injury', 'reaction_skin burning sensation', 'reaction_skin discolouration', 'reaction_skin disorder', 'reaction_skin irritation', 'reaction_skin laceration', 'reaction_skin lesion', 'reaction_skin odour abnormal', 'reaction_skin reaction', 'reaction_skin tightness', 'reaction_sleep apnoea syndrome', 'reaction_sleep disorder', 'reaction_sluggishness', 'reaction_sneezing', 'reaction_somnolence', 'reaction_speech disorder', 'reaction_spinal column stenosis', 'reaction_spinal cord injury', 'reaction_spinal pain', 'reaction_staphylococcal infection', 'reaction_stomach discomfort', 'reaction_stomatitis', 'reaction_strabismus', 'reaction_stupor', 'reaction_suicidal ideation', 'reaction_supraventricular extrasystoles', 'reaction_supraventricular tachycardia', 'reaction_surgery', 'reaction_suture insertion', 'reaction_swelling', 'reaction_swelling face', 'reaction_swollen tongue', 'reaction_syncope', 'reaction_systemic lupus erythematosus', 'reaction_tachycardia', 'reaction_taste disorder', 'reaction_tenderness', 'reaction_thermal burn', 'reaction_thinking abnormal', 'reaction_thirst', 'reaction_thought blocking', 'reaction_throat irritation', 'reaction_throat tightness', 'reaction_thrombosis', 'reaction_thyroxine decreased', 'reaction_tinnitus', 'reaction_tongue coated', 'reaction_tongue disorder', 'reaction_tonsillar hypertrophy', 'reaction_tonsillitis', 'reaction_tooth discolouration', 'reaction_tooth disorder', 'reaction_tooth injury', 'reaction_toothache', 'reaction_toxicity to various agents', 'reaction_tremor', 'reaction_trichorrhexis', 'reaction_trigeminal neuralgia', 'reaction_tunnel vision', 'reaction_ulcer', 'reaction_unresponsive to stimuli', 'reaction_upper respiratory tract infection', 'reaction_upper respiratory tract irritation', 'reaction_urinary hesitation', 'reaction_urinary incontinence', 'reaction_urinary tract infection', 'reaction_urine analysis abnormal', 'reaction_urine output decreased', 'reaction_urogenital disorder', 'reaction_urticaria', 'reaction_vaginal haemorrhage', 'reaction_vein discolouration', 'reaction_ventricular extrasystoles', 'reaction_vertigo', 'reaction_viral infection', 'reaction_viral test positive', 'reaction_vision blurred', 'reaction_visual acuity reduced', 'reaction_visual disturbance', 'reaction_visual impairment', 'reaction_vitamin b6 increased', 'reaction_vitreous floaters', 'reaction_vomiting', 'reaction_weight decreased', 'reaction_weight increased', 'reaction_wheezing', 'reaction_white blood cell count increased', 'outcome_allergic reaction', 'outcome_congenital anomaly', 'outcome_death', 'outcome_disability', 'outcome_hospitalization', 'outcome_life threatening', 'outcome_other outcome', 'outcome_other serious or important medical event', 'outcome_other serious outcome', 'outcome_required intervention', 'outcome_visited a health care provider', 'outcome_visited emergency room']</code></pre>
</div>
</div>
<p><strong>Data Summary:</strong></p>
<div id="cell-16" class="cell" data-outputid="e1f02d42-8e94-4ff0-cf12-9013956684c7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> df.describe(include<span class="op">=</span><span class="st">'all'</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="77">

  <div id="df-a8bc04b4-4d31-4ef2-ad5b-92cf6c6413c1" class="colab-df-container">
    <div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">outcomes</th>
<th data-quarto-table-cell-role="th">date_created</th>
<th data-quarto-table-cell-role="th">reactions</th>
<th data-quarto-table-cell-role="th">date_started</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">product_name_brand</th>
<th data-quarto-table-cell-role="th">outcome_allergic reaction</th>
<th data-quarto-table-cell-role="th">outcome_congenital anomaly</th>
<th data-quarto-table-cell-role="th">outcome_death</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">reaction_visual acuity reduced</th>
<th data-quarto-table-cell-role="th">reaction_visual disturbance</th>
<th data-quarto-table-cell-role="th">reaction_visual impairment</th>
<th data-quarto-table-cell-role="th">reaction_vitamin b6 increased</th>
<th data-quarto-table-cell-role="th">reaction_vitreous floaters</th>
<th data-quarto-table-cell-role="th">reaction_vomiting</th>
<th data-quarto-table-cell-role="th">reaction_weight decreased</th>
<th data-quarto-table-cell-role="th">reaction_weight increased</th>
<th data-quarto-table-cell-role="th">reaction_wheezing</th>
<th data-quarto-table-cell-role="th">reaction_white blood cell count increased</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>1020</td>
<td>1020</td>
<td>1020</td>
<td>1020</td>
<td>1020.000000</td>
<td>1020</td>
<td>1020</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>...</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.0</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.000000</td>
<td>1020.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>12</td>
<td>NaN</td>
<td>253</td>
<td>NaN</td>
<td>NaN</td>
<td>4</td>
<td>763</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>other outcome</td>
<td>NaN</td>
<td>diarrhoea</td>
<td>NaN</td>
<td>NaN</td>
<td>Female</td>
<td>diet coke</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>390</td>
<td>NaN</td>
<td>86</td>
<td>NaN</td>
<td>NaN</td>
<td>563</td>
<td>35</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>NaN</td>
<td>2015-07-11 00:55:03.529411840</td>
<td>NaN</td>
<td>2015-01-07 16:38:07.058823680</td>
<td>38.423549</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000980</td>
<td>0.000980</td>
<td>0.004902</td>
<td>...</td>
<td>0.001961</td>
<td>0.002941</td>
<td>0.000980</td>
<td>0.000980</td>
<td>0.0</td>
<td>0.082353</td>
<td>0.001961</td>
<td>0.000980</td>
<td>0.000980</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>NaN</td>
<td>2003-05-07 00:00:00</td>
<td>NaN</td>
<td>1959-07-28 00:00:00</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>NaN</td>
<td>2009-11-27 06:00:00</td>
<td>NaN</td>
<td>2009-05-24 12:00:00</td>
<td>24.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>NaN</td>
<td>2016-03-29 00:00:00</td>
<td>NaN</td>
<td>2015-11-24 12:00:00</td>
<td>40.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>NaN</td>
<td>2021-02-25 18:00:00</td>
<td>NaN</td>
<td>2020-09-10 00:00:00</td>
<td>53.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>NaN</td>
<td>2024-07-27 00:00:00</td>
<td>NaN</td>
<td>2024-07-26 00:00:00</td>
<td>90.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>...</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.0</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>19.780855</td>
<td>NaN</td>
<td>NaN</td>
<td>0.031311</td>
<td>0.031311</td>
<td>0.069876</td>
<td>...</td>
<td>0.044259</td>
<td>0.054179</td>
<td>0.031311</td>
<td>0.031311</td>
<td>0.0</td>
<td>0.275037</td>
<td>0.044259</td>
<td>0.031311</td>
<td>0.031311</td>
<td>0.0</td>
</tr>
</tbody>
</table>

<p>11 rows × 530 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-a8bc04b4-4d31-4ef2-ad5b-92cf6c6413c1')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-a8bc04b4-4d31-4ef2-ad5b-92cf6c6413c1 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-a8bc04b4-4d31-4ef2-ad5b-92cf6c6413c1');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-0b089564-98b9-4329-8aaf-4ee698ff2349">
  <button class="colab-df-quickchart" onclick="quickchart('df-0b089564-98b9-4329-8aaf-4ee698ff2349')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-0b089564-98b9-4329-8aaf-4ee698ff2349 button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>

  <div id="id_5a832906-65c0-4e12-85b5-f84b7fda4243">
    <style>
      .colab-df-generate {
        background-color: #E8F0FE;
        border: none;
        border-radius: 50%;
        cursor: pointer;
        display: none;
        fill: #1967D2;
        height: 32px;
        padding: 0 0 0 0;
        width: 32px;
      }

      .colab-df-generate:hover {
        background-color: #E2EBFA;
        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
        fill: #174EA6;
      }

      [theme=dark] .colab-df-generate {
        background-color: #3B4455;
        fill: #D2E3FC;
      }

      [theme=dark] .colab-df-generate:hover {
        background-color: #434B5C;
        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
        fill: #FFFFFF;
      }
    </style>
    <button class="colab-df-generate" onclick="generateWithVariable('summary')" title="Generate code using this dataframe." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <path d="M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z"></path>
  </svg>
    </button>
    <script>
      (() => {
      const buttonEl =
        document.querySelector('#id_5a832906-65c0-4e12-85b5-f84b7fda4243 button.colab-df-generate');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      buttonEl.onclick = () => {
        google.colab.notebook.generateWithVariable('summary');
      }
      })();
    </script>
  </div>

    </div>
  </div>
</div>
</div>
<p>From last summary table, we find some descriptive insights:</p>
<section id="key-descriptive-insights" class="level3">
<h3 class="anchored" data-anchor-id="key-descriptive-insights"><strong>Key Descriptive Insights</strong></h3>
<ol type="1">
<li><p><strong>Data Overview</strong>: The dataset contains <strong>1,020 records</strong> and <strong>530 features</strong>, including timestamps, categorical variables, and one-hot encoded <code>reaction_</code> and <code>outcome_</code> variables.</p></li>
<li><p><strong>Time Coverage</strong>: Most records are from <strong>2010 onward</strong>, but <code>date_started</code> has an outlier of 1959.</p></li>
<li><p><strong>Demographics</strong>: <strong>Median age is 38.42 years</strong>, with cases ranging from <strong>1 to 90 years</strong> (possible outliers). <strong>Female cases are the most common(563 occurrences)</strong>.</p></li>
<li><p><strong>Product Insights</strong>: The dataset includes <strong>763 unique brands</strong>, with <code>diet coke</code> appearing most frequently (35 times).</p></li>
<li><p><strong>Common Reactions</strong>: <code>diarrhoea</code> is the most frequently reported reaction (86 cases), while <code>reaction_vomiting</code> occurs relatively often (mean = 0.082).</p></li>
<li><p><strong>Severe Outcomes</strong>: <strong>Death is recorded in 0.5% of cases</strong>, and <strong>allergic reactions occur in 0.1%</strong>, indicating some high-risk cases in the dataset.</p></li>
</ol>
<p><strong>Age Group Distribution:</strong></p>
<div id="cell-20" class="cell" data-outputid="94253a4c-4b91-47de-c0e8-5fb303a10755">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'age'</span>] <span class="op">=</span> pd.to_numeric(df[<span class="st">'age'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> [<span class="dv">0</span>, <span class="dv">18</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>, <span class="dv">70</span>, <span class="dv">80</span>, <span class="dv">100</span>]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'&lt;18'</span>, <span class="st">'18-29'</span>, <span class="st">'30-39'</span>, <span class="st">'40-49'</span>, <span class="st">'50-59'</span>, <span class="st">'60-69'</span>, <span class="st">'70-79'</span>, <span class="st">'80+'</span>]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'age_group'</span>] <span class="op">=</span> pd.cut(df[<span class="st">'age'</span>], bins<span class="op">=</span>bins, labels<span class="op">=</span>labels, right<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'age_group'</span>, order<span class="op">=</span>labels, palette<span class="op">=</span><span class="st">"viridis"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Age Group Distribution'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Age Group'</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)
&lt;ipython-input-78-c1a57db86da3&gt;:8: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.countplot(data=df, x='age_group', order=labels, palette="viridis")</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-10-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>It is easily found that:</p>
<ul>
<li>The distribution of the population is mainly concentrated in the two intervals of &lt;18 and 40-49.</li>
<li>It declines sharply after the age of 50-59 years.</li>
</ul>
<div id="cell-22" class="cell" data-outputid="bcd25c95-6a60-4106-9c51-fbcb49ee7685">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create subplots</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span>df[<span class="st">'age'</span>], color<span class="op">=</span><span class="st">"lightcoral"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Age"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Age"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span>df[<span class="st">'date_started'</span>].<span class="bu">map</span>(pd.Timestamp.toordinal), color<span class="op">=</span><span class="st">"skyblue"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of Date Started"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Date Started"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plots</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Initial Insights from Boxplots:</p>
<p>1, Age Distribution:</p>
<ul>
<li>Most cases are from adults (20-60 years old).</li>
<li>Some outliers exist, including very young (0 years) and very old (80+ years) cases.</li>
</ul>
<p>2, Date Started Distribution:</p>
<ul>
<li><p>Most reports are from 2000 onwards, with a peak around 2010-2020.</p></li>
<li><p>few very old cases (1960s-1990s) may be historical records or data errors.</p></li>
</ul>
<p><strong>Top 10 reported Brands:</strong></p>
<div id="cell-25" class="cell" data-outputid="d5730196-f672-4bb9-efda-746a7490a216">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Top10_food <span class="op">=</span> df[<span class="st">'product_name_brand'</span>].value_counts().head(<span class="dv">10</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>top10_foodp <span class="op">=</span> Top10_food.plot(kind<span class="op">=</span><span class="st">'barh'</span>, title<span class="op">=</span><span class="st">"Top 10 Reported Brands"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>(Top10_food):</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    top10_foodp.text(value <span class="op">+</span> <span class="fl">0.5</span>, index, <span class="bu">str</span>(<span class="bu">int</span>(value)), va<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Diet Coke is showing a faulty lead.</p>
<div id="cell-27" class="cell" data-outputid="e9856114-d526-4b22-b69a-092aff49209a">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'year_created'</span>] <span class="op">=</span> df[<span class="st">'date_created'</span>].dt.year</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>product_trend <span class="op">=</span> df.groupby([<span class="st">'year_created'</span>, <span class="st">'product_name_brand'</span>]).size().reset_index(name<span class="op">=</span><span class="st">'count'</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>top_products <span class="op">=</span> df[<span class="st">'product_name_brand'</span>].value_counts().nlargest(<span class="dv">10</span>).index</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>product_trend_filtered <span class="op">=</span> product_trend[product_trend[<span class="st">'product_name_brand'</span>].isin(top_products)]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>product_trend_filtered, x<span class="op">=</span><span class="st">'year_created'</span>, y<span class="op">=</span><span class="st">'count'</span>, hue<span class="op">=</span><span class="st">'product_name_brand'</span>, marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Trend of Top 10 Reported Products Over Time"</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Reports"</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">"Product Name"</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['year_created'] = df['date_created'].dt.year</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-13-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With the exception of heavy fluctuation of Diet Coke and Exemption 4, the rest brands are basically stable between 0 and 2 across years</p>
<p><strong>Top 10 Reactions:</strong></p>
<div id="cell-30" class="cell" data-outputid="8aa2f0f0-f5b4-4287-d5e5-a5c283fde093">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>top10_r <span class="op">=</span> df[<span class="st">'reactions'</span>].value_counts().head(<span class="dv">10</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>top10_r.index <span class="op">=</span> top10_r.index.<span class="bu">str</span>.replace(<span class="st">'reaction_'</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>top10_rp <span class="op">=</span> top10_r.plot(kind<span class="op">=</span><span class="st">'barh'</span>, title<span class="op">=</span><span class="st">"Top 10 Reactions"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Reaction'</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Count'</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>(top10_r):</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    top10_rp.text(value <span class="op">+</span> <span class="fl">0.5</span>, index, <span class="bu">str</span>(<span class="bu">int</span>(value)), va<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>we found that nausea, vomiting, and diarrhoea are the most common reactions.</p>
<div id="cell-32" class="cell" data-outputid="5a315a0f-aa80-4d91-8882-df0251c5e493">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reaction_trend <span class="op">=</span> df.groupby([<span class="st">'year_created'</span>, <span class="st">'reactions'</span>]).size().reset_index(name<span class="op">=</span><span class="st">'count'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>top_reaction <span class="op">=</span> df[<span class="st">'reactions'</span>].value_counts().nlargest(<span class="dv">10</span>).index</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>reaction_trend_filtered <span class="op">=</span> reaction_trend[reaction_trend[<span class="st">'reactions'</span>].isin(top_reaction)]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>reaction_trend_filtered, x<span class="op">=</span><span class="st">'year_created'</span>, y<span class="op">=</span><span class="st">'count'</span>, hue<span class="op">=</span><span class="st">'reactions'</span>, marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Trend of Top 10 Reported reaction Over Time"</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Reports"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">"Reactions Name"</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.05</span>, <span class="dv">1</span>), loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With the exception of heavy fluctuation of nausea, diarrhoea, and vomiting, the rest reactions are basically stable between 0 and 4 across years.</p>
<p><strong>Health Outcomes Distribution:</strong></p>
<div id="cell-35" class="cell" data-outputid="b6ce3acb-276e-4f5f-9b95-548f63763386">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>outcome_cols <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> <span class="st">'outcome_'</span> <span class="kw">in</span> col]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>outcome_counts <span class="op">=</span> df[outcome_cols].<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>outcome_counts.index <span class="op">=</span> outcome_counts.index.<span class="bu">str</span>.replace(<span class="st">'outcome_'</span>, <span class="st">''</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>,<span class="dv">5</span>))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>outcome_countsp <span class="op">=</span> outcome_counts.plot(kind<span class="op">=</span><span class="st">'barh'</span>, title<span class="op">=</span><span class="st">"Health Outcomes Distribution"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>(outcome_counts):</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    outcome_countsp.text(value <span class="op">+</span> <span class="fl">0.5</span>, index, <span class="bu">str</span>(<span class="bu">int</span>(value)), va<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the bar chart of above, the least frequent outcomes include “congenital anomaly” and “allergic reaction,” each with only 1 occurrence.</p>
<p><strong>Correlation Analysis:</strong></p>
<div id="cell-38" class="cell" data-outputid="a97d72ab-db0d-48d9-e53c-6ebca8e53663">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>reaction_cols <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> <span class="st">'reaction_'</span> <span class="kw">in</span> col]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reaction_counts <span class="op">=</span> df[reaction_cols].<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>top_10_reactions <span class="op">=</span> reaction_counts.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>).index</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>top10_columns <span class="op">=</span> <span class="bu">list</span>(top_10_reactions)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>correlation_subset <span class="op">=</span> df[top10_columns].corr()</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>clean_reactions <span class="op">=</span> [col.replace(<span class="st">'reaction_'</span>, <span class="st">''</span>) <span class="cf">for</span> col <span class="kw">in</span> top_10_reactions]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>correlation_subset.index <span class="op">=</span> clean_reactions</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>correlation_subset.columns <span class="op">=</span> clean_reactions</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>sns.heatmap(correlation_subset, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, fmt<span class="op">=</span><span class="st">".2f"</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation Heatmap (Top 10 Reactions)"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This heatmap shows that The absence of concurrent symptoms was demonstrated.</p>
<div id="cell-40" class="cell" data-outputid="1a1c16d9-c0a3-4a3f-9ae6-51cc579093ec">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>selected_columns2 <span class="op">=</span> <span class="bu">list</span>(top_10_reactions) <span class="op">+</span> outcome_cols</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>correlation_subset2 <span class="op">=</span> df[selected_columns2].corr()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>correlation_subset_reformatted <span class="op">=</span> correlation_subset2.loc[outcome_cols, top_10_reactions]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>clean_outcomes <span class="op">=</span> [col.replace(<span class="st">'outcome_'</span>, <span class="st">''</span>) <span class="cf">for</span> col <span class="kw">in</span> outcome_cols]</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>correlation_subset_reformatted.index <span class="op">=</span> clean_outcomes</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>correlation_subset_reformatted.columns <span class="op">=</span> clean_reactions</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>sns.heatmap(correlation_subset_reformatted, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, fmt<span class="op">=</span><span class="st">".2f"</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Correlation Heatmap (Top 10 Reactions &amp; Outcomes)"</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Top 10 Reactions"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Outcomes"</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Obvious relationship between congenital anomaly and nausea is shown, also combined with some other significant relation such as death and abdominal pain upper, we could make further research on them.</p>
<div id="cell-42" class="cell" data-outputid="f5aad43b-efb5-4a7e-dcb4-373c57aca369">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'gender'</span>, y<span class="op">=</span><span class="st">'age'</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"age vs gender"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"gender"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"age"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">"age vs gender"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend(title="age vs gender")</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="AdvanceDS_Project1_files/figure-html/cell-19-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>the age distribution of male and female is a little different. There are more higher aged male than female. Besides this, the age distribution of male is more even than female</p>
</section>
</section>
<section id="feature-engineering-process" class="level1">
<h1><strong>Feature engineering process</strong></h1>
<p>Time-based Feature Engineering</p>
<div id="cell-46" class="cell" data-outputid="a020ca86-a505-4e7e-d48c-08ba8a97f62a">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate time difference between report and incident</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'report_delay'</span>] <span class="op">=</span> (df[<span class="st">'date_created'</span>] <span class="op">-</span> df[<span class="st">'date_started'</span>]).dt.days</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract temporal features</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'report_year'</span>] <span class="op">=</span> df[<span class="st">'date_created'</span>].dt.year</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'report_month'</span>] <span class="op">=</span> df[<span class="st">'date_created'</span>].dt.month</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'report_weekday'</span>] <span class="op">=</span> df[<span class="st">'date_created'</span>].dt.weekday</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'report_quarter'</span>] <span class="op">=</span> df[<span class="st">'date_created'</span>].dt.quarter</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create season feature</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'season'</span>] <span class="op">=</span> df[<span class="st">'report_month'</span>].<span class="bu">map</span>({</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>: <span class="st">'Winter'</span>, <span class="dv">2</span>: <span class="st">'Winter'</span>, <span class="dv">3</span>: <span class="st">'Spring'</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">4</span>: <span class="st">'Spring'</span>, <span class="dv">5</span>: <span class="st">'Spring'</span>, <span class="dv">6</span>: <span class="st">'Summer'</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="dv">7</span>: <span class="st">'Summer'</span>, <span class="dv">8</span>: <span class="st">'Summer'</span>, <span class="dv">9</span>: <span class="st">'Fall'</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10</span>: <span class="st">'Fall'</span>, <span class="dv">11</span>: <span class="st">'Fall'</span>, <span class="dv">12</span>: <span class="st">'Winter'</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Check time-based features</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Time-based Features Summary:"</span>)</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Report Delay Statistics:"</span>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'report_delay'</span>].describe())</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Temporal Distribution:"</span>)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Year distribution:"</span>, df[<span class="st">'report_year'</span>].value_counts().sort_index().head())</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Season distribution:"</span>, df[<span class="st">'season'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Time-based Features Summary:

Report Delay Statistics:
count     1020.000000
mean       184.345098
std       1068.350234
min         -4.000000
25%          2.000000
50%          6.000000
75%         26.000000
max      22391.000000
Name: report_delay, dtype: float64

Temporal Distribution:
Year distribution: report_year
2003     3
2004    38
2005    23
2006    48
2007    65
Name: count, dtype: int64
Season distribution: season
Spring    285
Summer    280
Winter    228
Fall      227
Name: count, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['report_delay'] = (df['date_created'] - df['date_started']).dt.days
&lt;ipython-input-87-aa7911eedc70&gt;:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['report_year'] = df['date_created'].dt.year
&lt;ipython-input-87-aa7911eedc70&gt;:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['report_month'] = df['date_created'].dt.month
&lt;ipython-input-87-aa7911eedc70&gt;:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['report_weekday'] = df['date_created'].dt.weekday
&lt;ipython-input-87-aa7911eedc70&gt;:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['report_quarter'] = df['date_created'].dt.quarter
&lt;ipython-input-87-aa7911eedc70&gt;:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['season'] = df['report_month'].map({</code></pre>
</div>
</div>
<p>Product Feature Engineering</p>
<div id="cell-48" class="cell" data-outputid="bcdd2731-bdfe-40a7-b634-5541e72ce2bb">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract product categories</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> categorize_product(name):</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    name <span class="op">=</span> <span class="bu">str</span>(name).lower()</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'water'</span> <span class="kw">in</span> name:</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Water'</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">any</span>(x <span class="kw">in</span> name <span class="cf">for</span> x <span class="kw">in</span> [<span class="st">'energy'</span>, <span class="st">'monster'</span>, <span class="st">'red bull'</span>]):</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Energy Drink'</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">any</span>(x <span class="kw">in</span> name <span class="cf">for</span> x <span class="kw">in</span> [<span class="st">'cola'</span>, <span class="st">'pepsi'</span>, <span class="st">'coke'</span>]):</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Cola'</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">'gatorade'</span> <span class="kw">in</span> name:</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Sports Drink'</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Other'</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'product_category'</span>] <span class="op">=</span> df[<span class="st">'product_name_brand'</span>].<span class="bu">apply</span>(categorize_product)</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create brand feature</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> extract_brand(name):</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    name <span class="op">=</span> <span class="bu">str</span>(name).lower()</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    major_brands <span class="op">=</span> [<span class="st">'coca-cola'</span>, <span class="st">'pepsi'</span>, <span class="st">'monster'</span>, <span class="st">'gatorade'</span>, <span class="st">'red bull'</span>,</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>                   <span class="st">'dasani'</span>, <span class="st">'aquafina'</span>, <span class="st">'poland spring'</span>]</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> brand <span class="kw">in</span> major_brands:</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> brand <span class="kw">in</span> name:</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> brand</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">'other'</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'brand'</span>] <span class="op">=</span> df[<span class="st">'product_name_brand'</span>].<span class="bu">apply</span>(extract_brand)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Check product features</span></span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Product Features Summary:"</span>)</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Product Category Distribution:"</span>)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'product_category'</span>].value_counts())</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Brand Distribution:"</span>)</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'brand'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Product Features Summary:

Product Category Distribution:
product_category
Other           403
Water           323
Cola            170
Energy Drink     78
Sports Drink     46
Name: count, dtype: int64

Brand Distribution:
brand
other            826
pepsi             47
gatorade          46
monster           26
poland spring     22
red bull          16
coca-cola         13
aquafina          12
dasani            12
Name: count, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['product_category'] = df['product_name_brand'].apply(categorize_product)
&lt;ipython-input-88-50e6e31ea299&gt;:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['brand'] = df['product_name_brand'].apply(extract_brand)</code></pre>
</div>
</div>
<p>Age Feature Engineering</p>
<div id="cell-50" class="cell" data-outputid="cfad7498-9790-4362-a845-780202334d37">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create binary features for vulnerable age groups</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'is_minor'</span>] <span class="op">=</span> (df[<span class="st">'age'</span>] <span class="op">&lt;</span> <span class="dv">18</span>).astype(<span class="bu">int</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'is_elderly'</span>] <span class="op">=</span> (df[<span class="st">'age'</span>] <span class="op">&gt;=</span> <span class="dv">65</span>).astype(<span class="bu">int</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check age features</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Age Features Summary:"</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Age Group Counts:"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Minors (&lt; 18):"</span>, df[<span class="st">'is_minor'</span>].<span class="bu">sum</span>())</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Elderly (&gt;= 65):"</span>, df[<span class="st">'is_elderly'</span>].<span class="bu">sum</span>())</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Age Statistics by Category:"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.groupby(<span class="st">'product_category'</span>)[<span class="st">'age'</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Age Features Summary:

Age Group Counts:
Minors (&lt; 18): 197
Elderly (&gt;= 65): 104

Age Statistics by Category:
                  count       mean        std   min    25%   50%    75%   max
product_category                                                             
Cola              170.0  41.806882  17.556928   5.0  28.55  43.0  54.00  90.0
Energy Drink       78.0  32.943462  13.438449  12.0  24.69  32.5  41.75  84.0
Other             403.0  36.331017  20.584822   1.0  20.00  38.0  51.00  89.0
Sports Drink       46.0  31.560870  18.588867   5.8  16.50  28.0  44.00  84.0
Water             323.0  41.554365  20.509124   1.0  27.00  44.0  56.00  89.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['is_minor'] = (df['age'] &lt; 18).astype(int)
&lt;ipython-input-89-ff7da351de43&gt;:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['is_elderly'] = (df['age'] &gt;= 65).astype(int)</code></pre>
</div>
</div>
<p>Reaction Severity Score</p>
<div id="cell-52" class="cell" data-outputid="d848a4c4-2ef8-4e5b-a12f-5619d3e1ee35">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate reaction count</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>reaction_cols <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> col.startswith(<span class="st">'reaction_'</span>)]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'reaction_count'</span>] <span class="op">=</span> df[reaction_cols].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create severity score</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>outcome_cols <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> df.columns <span class="cf">if</span> col.startswith(<span class="st">'outcome_'</span>)]</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>outcome_weights <span class="op">=</span> {</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_death'</span>: <span class="dv">5</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_life threatening'</span>: <span class="dv">4</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_hospitalization'</span>: <span class="dv">3</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_disability'</span>: <span class="dv">3</span>,</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_required intervention'</span>: <span class="dv">2</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_visited emergency room'</span>: <span class="dv">2</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_visited a health care provider'</span>: <span class="dv">1</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'outcome_other outcome'</span>: <span class="dv">1</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'severity_score'</span>] <span class="op">=</span> <span class="bu">sum</span>(df[col] <span class="op">*</span> weight</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>                          <span class="cf">for</span> col, weight <span class="kw">in</span> outcome_weights.items()</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>                          <span class="cf">if</span> col <span class="kw">in</span> df.columns)</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Check severity features</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Severity Features Summary:"</span>)</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Reaction Count Statistics:"</span>)</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'reaction_count'</span>].describe())</span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Severity Score Statistics:"</span>)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'severity_score'</span>].describe())</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Average Severity by Product Category:"</span>)</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.groupby(<span class="st">'product_category'</span>)[<span class="st">'severity_score'</span>].mean().sort_values(ascending<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Severity Features Summary:

Reaction Count Statistics:
count    1020.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: reaction_count, dtype: float64

Severity Score Statistics:
count    1020.000000
mean        1.276471
std         1.011240
min         0.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         5.000000
Name: severity_score, dtype: float64

Average Severity by Product Category:
product_category
Energy Drink    1.435897
Sports Drink    1.326087
Water           1.281734
Cola            1.258824
Other           1.243176
Name: severity_score, dtype: float64</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['reaction_count'] = df[reaction_cols].sum(axis=1)
&lt;ipython-input-90-1dcae1789d64&gt;:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['severity_score'] = sum(df[col] * weight</code></pre>
</div>
</div>
<p>Standardize Numerical Features</p>
<div id="cell-54" class="cell" data-outputid="a6b78429-d3cb-46c0-a75c-4890dcb734f8">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>numeric_features <span class="op">=</span> [<span class="st">'age'</span>, <span class="st">'reaction_count'</span>, <span class="st">'severity_score'</span>, <span class="st">'report_delay'</span>]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>df[numeric_features] <span class="op">=</span> scaler.fit_transform(df[numeric_features])</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check standardized features</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Standardized Features Summary:"</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> feature <span class="kw">in</span> numeric_features:</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>feature<span class="sc">}</span><span class="ss"> statistics after standardization:"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(df[feature].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Standardized Features Summary:

age statistics after standardization:
count    1.020000e+03
mean    -2.159493e-16
std      1.000491e+00
min     -1.892836e+00
25%     -7.295248e-01
50%      7.973489e-02
75%      7.372584e-01
max      2.608671e+00
Name: age, dtype: float64

reaction_count statistics after standardization:
count    1020.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: reaction_count, dtype: float64

severity_score statistics after standardization:
count    1.020000e+03
mean     8.533479e-17
std      1.000491e+00
min     -1.262902e+00
25%     -2.735318e-01
50%     -2.735318e-01
75%      7.158385e-01
max      3.683949e+00
Name: severity_score, dtype: float64

report_delay statistics after standardization:
count    1.020000e+03
mean     1.393221e-17
std      1.000491e+00
min     -1.763818e-01
25%     -1.707629e-01
50%     -1.670169e-01
75%     -1.482873e-01
max      2.079613e+01
Name: report_delay, dtype: float64</code></pre>
</div>
</div>
<p>Encode Categorical Variables</p>
<div id="cell-56" class="cell" data-outputid="74fac760-45ae-45b4-afff-5b96b69e80dd">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>categorical_features <span class="op">=</span> [<span class="st">'season'</span>, <span class="st">'product_category'</span>, <span class="st">'brand'</span>, <span class="st">'gender'</span>]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>df_encoded <span class="op">=</span> pd.get_dummies(df, columns<span class="op">=</span>categorical_features, prefix<span class="op">=</span>categorical_features)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check encoded features</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Encoded Features Summary:"</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Original shape:"</span>, df.shape)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Encoded shape:"</span>, df_encoded.shape)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">New encoded columns (sample):"</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_encoded.columns[<span class="op">-</span><span class="dv">20</span>:])  <span class="co"># Show last 20 columns as sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Encoded Features Summary:

Original shape: (1020, 544)
Encoded shape: (1020, 562)

New encoded columns (sample):
Index(['season_Summer', 'season_Winter', 'product_category_Cola',
       'product_category_Energy Drink', 'product_category_Other',
       'product_category_Sports Drink', 'product_category_Water',
       'brand_aquafina', 'brand_coca-cola', 'brand_dasani', 'brand_gatorade',
       'brand_monster', 'brand_other', 'brand_pepsi', 'brand_poland spring',
       'brand_red bull', 'gender_Female', 'gender_Male', 'gender_Not Reported',
       'gender_Unknown'],
      dtype='object')</code></pre>
</div>
</div>
<p>Create Interaction Features</p>
<div id="cell-58" class="cell" data-outputid="f6a106c2-08d7-42fb-f438-2c8568dd3fed">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df_encoded[<span class="st">'age_severity'</span>] <span class="op">=</span> df_encoded[<span class="st">'age'</span>] <span class="op">*</span> df_encoded[<span class="st">'severity_score'</span>]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>df_encoded[<span class="st">'reactions_delay'</span>] <span class="op">=</span> df_encoded[<span class="st">'reaction_count'</span>] <span class="op">*</span> df_encoded[<span class="st">'report_delay'</span>]</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check interaction features</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Interaction Features Summary:"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Age-Severity Interaction Statistics:"</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_encoded[<span class="st">'age_severity'</span>].describe())</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Reactions-Delay Interaction Statistics:"</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_encoded[<span class="st">'reactions_delay'</span>].describe())</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Final dataset summary</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Final Dataset Summary:"</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Final shape:"</span>, df_encoded.shape)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Memory usage:"</span>, df_encoded.memory_usage().<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">1024</span><span class="op">**</span><span class="dv">2</span>, <span class="st">"MB"</span>)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Sample of final features:"</span>)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_encoded.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Interaction Features Summary:

Age-Severity Interaction Statistics:
count    1020.000000
mean       -0.000417
std         0.957292
min        -4.827819
25%        -0.312343
50%        -0.018573
75%         0.351732
max         5.666388
Name: age_severity, dtype: float64

Reactions-Delay Interaction Statistics:
count    1020.0
mean        0.0
std         0.0
min        -0.0
25%         0.0
50%        -0.0
75%         0.0
max        -0.0
Name: reactions_delay, dtype: float64

Final Dataset Summary:
Final shape: (1020, 564)

Memory usage: 4.213443756103516 MB

Sample of final features:
                         outcomes date_created                      reactions  \
0           required intervention   2007-06-13                        anxiety   
1          visited emergency room   2004-03-26                       insomnia   
2                   other outcome   2007-02-20  obsessive-compulsive disorder   
3                   other outcome   2015-06-24                   restlessness   
4  visited a health care provider   2018-10-13                           pain   

  date_started       age                               product_name_brand  \
0   2007-03-20 -1.083576                                   diet coke soda   
1   2004-02-18 -1.538785  archer farms market xl cooler, orange pineapple   
2   2007-02-16  0.686680              sobe lean diet mango melon beverage   
3   2015-06-09 -1.741099                              acadia spring water   
4   2018-10-05  0.282050                                          mt. dew   

   outcome_allergic reaction  outcome_congenital anomaly  outcome_death  \
0                          0                           0              0   
1                          0                           0              0   
2                          0                           0              0   
3                          0                           0              0   
4                          0                           0              0   

   outcome_disability  ...  brand_other  brand_pepsi  brand_poland spring  \
0                   0  ...         True        False                False   
1                   0  ...         True        False                False   
2                   0  ...         True        False                False   
3                   0  ...         True        False                False   
4                   0  ...         True        False                False   

   brand_red bull  gender_Female  gender_Male  gender_Not Reported  \
0           False           True        False                False   
1           False           True        False                False   
2           False           True        False                False   
3           False          False         True                False   
4           False          False         True                False   

   gender_Unknown  age_severity  reactions_delay  
0           False     -0.775665             -0.0  
1           False     -1.101521             -0.0  
2           False     -0.187829             -0.0  
3           False      0.476246             -0.0  
4           False     -0.077150             -0.0  

[5 rows x 564 columns]</code></pre>
</div>
</div>
</section>
<section id="each-members-contribution" class="level1">
<h1><strong>Each member’s contribution</strong></h1>
<ul>
<li><p>Preach Apintanapong:</p></li>
<li><p>List item</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>